# ~/.config/starship.toml
add_newline = true

[character]
use_symbol_for_status = true  # Show "âœ–" when the command faild
symbol = "âœ "
style_success = "bold green"
style_failure = "bold red"
disabled = false

[directory]
truncation_length = 5
prefix = "in "

[docker_context]
symbol = "ğŸ‹ "
style = "bold blue"
only_with_files = false
disabled = false

[elixir]
symbol = "ğŸ”® "
style = "bold purple"

[elm]
symbol = "î˜¬ "
style = "bold cyan"
disabled = false

[erlang]
symbol = "ğŸ–§ "
style = "bold red"
disabled = false

[git_branch]
symbol = "î‚  "
truncation_symbol = ""
style = "bold yellow"

[git_state]
progress_divider = " of "

[git_commit]
only_detached = true
prefix = "("
suffix = ")"
style = "bold green"
commit_hash_length = 7

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ "
behind = "ğŸ¢ "
diverged = "ğŸ”± "
untracked = "ğŸ›¤ï¸  Ã—"
untracked_count.enabled = true
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—"
modified_count.enabled = true
staged = "ğŸ—ƒï¸  Ã—"
staged_count.enabled = true
renamed = "ğŸ“› Ã—"
renamed_count.enabled = true
deleted = "ğŸ—‘ï¸  Ã—"
deleted_count.enabled = true
prefix = "["
suffix = "]"
style = "bright-white"

[golang]
symbol = "ğŸ¹ "
style = "bold cyan"
disabled = false

[hostname]
ssh_only = false
prefix = "Â«"
suffix = "Â»"
trim_at = "-"
style = "bold dimmed white"
disabled = false

[java]
symbol = "â˜• "
style = "dimmed red"
disabled = false

[jobs]
symbol = "âœ¦ "
disabled = false

[julia]
symbol = "à®ƒ "
style = "bold purple"
disabled = false

[kubernetes]
symbol = "â›µ "
style = "dimmed green"
disabled = false

[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

[memory_usage]
show_percentage = true
show_swap = true
style = "bold dimmed white"
disabled = false

[nim]
symbol = "ğŸ‘‘ "
style = "bold yellow"
disabled = false

[nix_shell]
symbol = "â„ï¸ "
use_name = true
impure_msg = "impure"
pure_msg = "pure"
disabled = false

[nodejs]
symbol = "â¬¢ "
style = "bold green"
disabled = false

[package]
symbol = "ğŸ“¦ "
style = "bold 208"
display_private = true
disabled = false

[ocaml]
symbol = "ğŸª "
style = "bold yellow"
disabled = false

[php]
symbol = "ğŸ˜ "
style = "bold 147"
disabled = false

[python]
symbol = "ğŸ "
pyenv_version_name = true
pyenv_prefix = "pyenv "
scan_for_pyfiles = true
style = "bold blue"
disabled = false

[ruby]
symbol = "ğŸ’ "
style = "bold red"
disabled = false

[rust]
symbol = "ğŸ¦€"
style = "bold orange"
disabled = false

[singularity]
symbol = "ğŸ“¦ "
label = ""
prefix = "["
suffix = "]"
style = "bold dimmed blue"
disabled = false

[terraform]
symbol = "ğŸ’  "
show_version = false
style = "bold 105"
disabled = false

[time]
format = "ğŸ•™ %T"
use_12hr = true
style = "bright-white"
disabled = false

[username]
style_root = "bold red"
style_user = "bold dimmed blue"
show_always = true
disabled = false

[zig]
symbol = "âš¡ï¸ "
style = "bold yellow"
disabled = false

[aws]
style = "bold blue"
symbol = "ğŸ…° "
displayed_items = "region"

[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "va"
